export { default as Start } from './Start'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as ResetPassword } from './ResetPassword'
export { default as JoinRide } from './JoinRide'
export { default as Account } from './Account'
export {default as RideDetails} from './RideDetails'
export {default as StartRide} from './StartRide'